version: 2
updates:
  - package-ecosystem: gomod
    directory: /control-plane
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "go"]

  - package-ecosystem: npm
    directory: /console
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "console"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ["dependencies", "ci"]

  - package-ecosystem: docker
    directories:
      - /control-plane
      - /console
      - /image
    schedule:
      interval: weekly
    labels: ["dependencies", "docker"]
