import { Fragment, useCallback, useEffect, useRef, useState } from 'react'
import { api, App as TApp, Sandbox, Process, ConfigItem, Snapshot, AppEvent, GitStatus, GitFile, FileEntry, RuntimeSuggestion } from './api'
import { c, font, mono, Card, H, Btn, Pill, StatusPill, statusTone, Input, tab } from './design/kit'
import { DeployModal } from './DeployModal'

type Msg = { role: 'user' | 'agent'; text: string; taskId?: string; done?: boolean }
const TABS = ['overview', 'files', 'git', 'config', 'snapshots', 'activity'] as const
type Tab = (typeof TABS)[number]

// Per-app agent context (Layer 2). Platform/sandbox conventions come from the
// agent's system prompt (Settings → Agent system prompt); this file is only the
// APP-specific briefing: detected stack, upstream repo, how it runs.
function buildAppAgentsMd(app: TApp | null, pick: RuntimeSuggestion): string {
  const L: string[] = [
    `# ${app?.name || 'app'} — app guide`,
    '',
    "_Generated by sandboxd. Sandbox conventions & guardrails are in your system prompt; this is the app-specific context._",
    '',
    `- **Detected stack:** ${pick.preset}${pick.confidence ? ` (${pick.confidence} confidence)` : ''}`,
  ]
  if (app?.git?.repo_url) L.push(`- **Upstream repository:** ${app.git.repo_url}${app.git.branch ? ` (branch \`${app.git.branch}\`)` : ''} — read its README/docs before non-trivial changes.`)
  L.push('- **How it runs:** `sandbox.yaml` supervises the web process on `0.0.0.0:3000`; edit source and the platform restarts it.')
  L.push('- **Source:** the application source lives in this workspace — you may edit and rebuild it.')
  if (pick.notes?.length) L.push('', '## Notes', ...pick.notes.map((n) => `- ${n}`))
  if (pick.config_snippets?.length) L.push('', '## Config', ...pick.config_snippets.map((cs) => `- \`${cs.file}\`: ${cs.note}`))
  L.push('')
  return L.join('\n')
}

// Write AGENTS.md only if the repo doesn't already ship one (respect the user's
// file), and keep our generated file out of `git status` for imported repos.
async function ensureAppAgentsMd(sandboxId: string, app: TApp | null, pick: RuntimeSuggestion): Promise<void> {
  try {
    const existing = await api.getWorkspaceFile(sandboxId, 'AGENTS.md')
    if (existing !== null) return // don't touch the user's own AGENTS.md
    await api.putWorkspaceFile(sandboxId, 'workspace/app/AGENTS.md', buildAppAgentsMd(app, pick))
    if (app?.git) {
      const ex = (await api.getWorkspaceFile(sandboxId, '.git/info/exclude').catch(() => null)) || ''
      if (!ex.split('\n').includes('AGENTS.md')) {
        const sep = ex === '' || ex.endsWith('\n') ? '' : '\n'
        await api.putWorkspaceFile(sandboxId, 'workspace/app/.git/info/exclude', `${ex}${sep}AGENTS.md\n`).catch(() => undefined)
      }
    }
  } catch { /* app context is advisory — never block the runtime apply */ }
}

export function AppView({
  appId, initialTab, onError, toast, goApps, goSettings,
}: { appId: string; initialTab?: string; onError: (m: string) => void; toast: (m: string) => void; goApps: () => void; goSettings: () => void }) {
  const [app, setApp] = useState<TApp | null>(null)
  const [sb, setSb] = useState<Sandbox | null>(null)
  const [tabName, setTabName] = useState<Tab>((initialTab as Tab) || 'overview')
  const [busy, setBusy] = useState(false)
  const [menu, setMenu] = useState(false)
  const [applied, setApplied] = useState<{ preset: string } | null>(null) // auto-applied runtime banner (Undo)
  const [deployOpen, setDeployOpen] = useState(false)
  const autoRef = useRef<string>('') // guards one auto-apply attempt per sandbox

  const refresh = useCallback(async () => {
    try {
      const a = await api.getApp(appId)
      setApp(a)
      setSb(a.current_sandbox_id ? await api.getSandbox(a.current_sandbox_id) : null)
    } catch (e) { onError((e as Error).message) }
  }, [appId, onError])
  useEffect(() => { refresh() }, [refresh])
  // Poll fast while anything is in flight (sandbox starting/stopping, or the dev
  // server not yet answering the preview probe) so first-run readiness surfaces
  // quickly; back off once it's settled.
  const settled = sb?.status === 'running' && sb?.preview?.status === 'ready'
  useEffect(() => {
    const t = setInterval(refresh, settled ? 5000 : 2000)
    return () => clearInterval(t)
  }, [refresh, settled])

  // Detect → apply the recommended sandbox.yaml + write an app-context AGENTS.md
  // for the agent, then restart. Shared by the auto-apply-on-import path and the
  // manual button. Never overrides an authoritative manifest / existing AGENTS.md.
  const applyRuntime = useCallback(async (sandboxId: string, opts: { auto: boolean }): Promise<boolean> => {
    const insp = await api.runtimeInspect(appId)
    if (insp.existing_manifest?.present) { if (!opts.auto) toast('This app already has a sandbox.yaml'); return false }
    const pick = insp.suggestions.find((s) => s.preset === insp.default_suggestion && s.suggested_manifest)
      || insp.suggestions.find((s) => s.suggested_manifest && (opts.auto ? s.confidence === 'high' : true))
    if (!pick?.suggested_manifest) { if (!opts.auto) onError('No runtime could be confidently detected — add a sandbox.yaml manually'); return false }
    await api.putWorkspaceFile(sandboxId, 'workspace/app/sandbox.yaml', pick.suggested_manifest)
    await ensureAppAgentsMd(sandboxId, app, pick) // per-app agent context (best-effort)
    await api.stopSandbox(sandboxId).catch(() => undefined)
    await api.startSandbox(sandboxId)
    setApplied({ preset: pick.preset })
    toast(`Detected ${pick.preset} — applied runtime`)
    await refresh()
    return true
  }, [appId, app, onError, toast, refresh])

  // Auto-apply once per sandbox: git-imported app + running sandbox + no manifest.
  useEffect(() => {
    if (!app?.git || !sb || sb.status !== 'running') return
    if (autoRef.current === sb.id) return
    autoRef.current = sb.id
    applyRuntime(sb.id, { auto: true }).catch(() => { /* advisory; ignore */ })
  }, [app?.git, sb, applyRuntime])

  const undoRuntime = useCallback(async () => {
    if (!sb) return
    setBusy(true)
    try {
      await api.putWorkspaceFile(sb.id, 'workspace/app/sandbox.yaml', '')
      await api.stopSandbox(sb.id).catch(() => undefined)
      await api.startSandbox(sb.id)
      setApplied(null); toast('Reverted to defaults'); await refresh()
    } catch (e) { onError((e as Error).message) } finally { setBusy(false) }
  }, [sb, onError, toast, refresh])

  if (!app) return <div style={{ padding: 40, color: c.muted2 }}>Loading…</div>
  const status = sb?.status
  const previewURL = sb?.preview?.url

  const act = async (fn: () => Promise<unknown>, ok?: string) => {
    setBusy(true)
    try { await fn(); await refresh(); if (ok) toast(ok) } catch (e) { onError((e as Error).message) } finally { setBusy(false) }
  }
  const snapshot = () => { if (sb) act(() => api.createSnapshot(sb.id, `${app.name}-${Date.now()}`), 'Snapshot captured') }
  const renameApp = async () => {
    if (!app) return
    const next = window.prompt('Rename app', app.name)?.trim()
    if (!next || next === app.name) return
    try { setApp(await api.updateApp(appId, { name: next })); toast('Renamed') }
    catch (e) { onError((e as Error).message) }
  }

  const tabBadge: Record<Tab, string> = { overview: '', files: '', git: '', config: '', snapshots: '', activity: '' }

  return (
    <div style={{ maxWidth: 1320, margin: '0 auto', padding: '28px 40px 80px' }}>
      <div style={{ fontSize: 12, color: c.muted2, marginBottom: 10 }}>
        <a onClick={goApps} className="dc-hoverink" style={{ color: c.muted, cursor: 'pointer', textDecoration: 'none' }}>Apps</a>
        <span style={{ margin: '0 4px' }}>/</span><span style={{ color: c.fg }}>{app.name}</span>
      </div>

      {/* header */}
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 14, marginBottom: 20, flexWrap: 'wrap' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <h1 onDoubleClick={renameApp} title="Double-click to rename" style={{ fontFamily: font.display, fontSize: 26, fontWeight: 700, margin: 0, cursor: 'text' }}>{app.name}</h1>
            <button onClick={renameApp} title="Rename app" className="dc-hoverink" aria-label="Rename app" style={{ background: 'none', border: 'none', cursor: 'pointer', color: c.muted2, fontSize: 15, lineHeight: 1, padding: 2 }}>✎</button>
            {sb ? <StatusPill status={status} /> : <Pill tone="neutral">no sandbox</Pill>}
          </div>
          <div onClick={() => { if (sb) { navigator.clipboard?.writeText(sb.id); toast('Sandbox ID copied') } }} title="Copy sandbox ID" style={{ ...mono, fontSize: 11, color: c.muted2, marginTop: 2, cursor: 'pointer' }}>
            {sb ? `sb:${sb.id}` : app.id} <span style={{ fontSize: 10, color: c.faint }}>⧉</span>
          </div>
        </div>
        <div style={{ marginLeft: 'auto', display: 'flex', gap: 8, alignItems: 'center', position: 'relative' }}>
          {!sb && <Btn variant="primary" disabled={busy} onClick={() => act(() => api.createAppSandbox(appId))} sm>Create sandbox</Btn>}
          {sb && status === 'stopped' && <Btn disabled={busy} onClick={() => act(() => api.startSandbox(sb.id))}>Start</Btn>}
          {sb && status === 'running' && <Btn disabled={busy} onClick={() => act(() => api.stopSandbox(sb.id))}>Stop</Btn>}
          {previewURL && status === 'running' && <Btn onClick={() => window.open(previewURL, '_blank')}>Open ↗</Btn>}
          <button onClick={() => setDeployOpen(true)} data-testid="deploy-btn" className="dc-hoverborder" style={{ display: 'flex', alignItems: 'center', gap: 6, border: 'none', borderRadius: 7, padding: '6px 13px', cursor: 'pointer', background: 'linear-gradient(135deg,#3f3f46,#18181b)', color: '#fff', fontFamily: font.sans, fontSize: 12.5, fontWeight: 600 }}>
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2 4 6v6c0 5 3.4 8.5 8 10 4.6-1.5 8-5 8-10V6Z" opacity=".35" /><path d="m9 12 2 2 4-4" /></svg>
            Deploy
          </button>
          <Btn onClick={() => setMenu((m) => !m)} style={{ letterSpacing: 1 }}>⋯</Btn>
          {menu && (
            <Card style={{ position: 'absolute', top: 38, right: 0, padding: 4, minWidth: 180, zIndex: 40, boxShadow: '0 8px 24px rgba(0,0,0,.08)' }}>
              {sb && <MenuItem onClick={() => { setMenu(false); snapshot() }}>Take snapshot</MenuItem>}
              {previewURL && <MenuItem onClick={() => { navigator.clipboard?.writeText(previewURL); toast('Preview URL copied'); setMenu(false) }}>Copy preview URL</MenuItem>}
              <div style={{ height: 1, background: c.panel2, margin: '4px 0' }} />
              <MenuItem danger onClick={async () => { setMenu(false); if (!window.confirm(`Delete “${app.name}” and everything it owns? This cannot be undone.`)) return; try { await api.deleteApp(appId); toast('App deleted'); goApps() } catch (e) { onError((e as Error).message) } }}>Delete app…</MenuItem>
            </Card>
          )}
        </div>
      </div>

      {applied && (
        <div data-testid="runtime-applied-banner" style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', marginBottom: 18, borderRadius: 9, border: `1px solid ${c.border}`, background: c.panel2, fontSize: 12.5 }}>
          <Pill tone="good" dot>runtime applied</Pill>
          <span style={{ color: c.fg2 }}>Detected <b style={{ color: c.fg }}>{applied.preset}</b> and wrote a <span style={{ ...mono, fontSize: 11.5 }}>sandbox.yaml</span> so the preview boots — your source was not modified.</span>
          <a onClick={undoRuntime} className="dc-hoverink" style={{ marginLeft: 'auto', color: c.link, cursor: 'pointer' }}>Undo</a>
          <a onClick={() => setApplied(null)} className="dc-hoverink" style={{ color: c.muted2, cursor: 'pointer' }}>Dismiss</a>
        </div>
      )}

      {/* tabs */}
      <div style={{ display: 'flex', gap: 2, borderBottom: `1px solid ${c.border}`, marginBottom: 24 }}>
        {TABS.map((t) => (
          <div key={t} data-testid={`tab-${t}`} className="dc-hoverink" onClick={() => setTabName(t)} style={{ ...tab(tabName === t), textTransform: 'capitalize' }}>
            {t}{tabBadge[t] && <span style={{ ...mono, marginLeft: 6, fontSize: 10, color: c.muted2 }}>{tabBadge[t]}</span>}
          </div>
        ))}
      </div>

      {tabName === 'overview' && <Overview app={app} sb={sb} previewURL={previewURL} onError={onError} refresh={refresh} onApplyRuntime={() => sb && applyRuntime(sb.id, { auto: false })} canApply={status === 'running'} />}
      {tabName === 'files' && <FilesTab sb={sb} onError={onError} toast={toast} />}
      {tabName === 'git' && <GitTab appId={appId} onError={onError} toast={toast} goSettings={goSettings} />}
      {tabName === 'config' && <ConfigTab appId={appId} onError={onError} />}
      {tabName === 'snapshots' && <SnapshotsTab appId={appId} appName={app.name} onError={onError} toast={toast} refresh={refresh} sb={sb} />}
      {tabName === 'activity' && <ActivityTab appId={appId} onError={onError} />}
      {deployOpen && <DeployModal appName={app.name} close={() => setDeployOpen(false)} />}
    </div>
  )
}

function MenuItem({ children, onClick, danger }: { children: React.ReactNode; onClick: () => void; danger?: boolean }) {
  return <div onClick={onClick} style={{ padding: '7px 11px', borderRadius: 6, fontSize: 12.5, cursor: 'pointer', color: danger ? c.bad : c.fg }} onMouseEnter={(e) => (e.currentTarget.style.background = danger ? 'rgba(220,38,38,.06)' : c.panel2)} onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}>{children}</div>
}

// ---------- OVERVIEW (preview + processes + runtime + AGENT CHAT) ----------
function Overview({ app, sb, previewURL, onError, refresh, onApplyRuntime, canApply }: { app: TApp; sb: Sandbox | null; previewURL?: string; onError: (m: string) => void; refresh: () => void; onApplyRuntime: () => void; canApply: boolean }) {
  const running = sb?.status === 'running'
  const procs: Process[] = sb?.processes || []
  // The dev server isn't up the instant the sandbox is "running" — the control
  // plane HTTP-probes it and flips preview.status to "ready". Only mount the
  // iframe once ready (so it never caches a connection-refused page), and let it
  // remount whenever readiness toggles (e.g. the apply→restart cycle).
  const ready = running && !!previewURL && sb?.preview?.status === 'ready'
  const [nonce, setNonce] = useState(0) // manual "reload" bump
  const wasReady = useRef(false)
  useEffect(() => {
    if (ready && !wasReady.current) setNonce((n) => n + 1) // fresh load on first-ready
    wasReady.current = ready
  }, [ready])

  // Client-side reachability: the control plane already confirmed the app is up
  // (preview.status==='ready'), so if the BROWSER can't reach the same URL the
  // iframe is being blocked client-side — almost always HTTP being upgraded to
  // HTTPS on a plain-HTTP preview. Detect it and tell the user to open a new tab
  // instead of leaving a blank frame that looks broken.
  const [reach, setReach] = useState<'checking' | 'ok' | 'blocked'>('checking')
  useEffect(() => {
    if (!ready || !previewURL) { setReach('checking'); return }
    let cancelled = false
    setReach('checking')
    const ctrl = new AbortController()
    const timer = setTimeout(() => ctrl.abort(), 6000)
    fetch(previewURL, { mode: 'no-cors', cache: 'no-store', signal: ctrl.signal })
      .then(() => { if (!cancelled) setReach('ok') })
      .catch(() => { if (!cancelled) setReach('blocked') })
      .finally(() => clearTimeout(timer))
    return () => { cancelled = true; clearTimeout(timer); ctrl.abort() }
  }, [ready, previewURL, nonce])
  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 400px', gap: 16, alignItems: 'start' }}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {/* preview */}
        <Card style={{ overflow: 'hidden' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', borderBottom: `1px solid ${c.border}`, background: c.panel2 }}>
            <span onClick={() => { if (previewURL) { navigator.clipboard?.writeText(previewURL) } }} title="Copy URL" style={{ ...mono, fontSize: 11.5, color: c.muted, flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', cursor: 'pointer' }}>
              {previewURL || 'no preview'}{previewURL ? ' ⧉' : ''}
            </span>
            {ready && <a onClick={() => setNonce((n) => n + 1)} title="Reload preview" className="dc-hoverink" data-testid="preview-reload" style={{ color: c.muted, fontSize: 13, cursor: 'pointer' }}>↻</a>}
            {previewURL && running && <a onClick={() => window.open(previewURL, '_blank')} style={{ color: c.link, fontSize: 12, cursor: 'pointer' }}>Open ↗</a>}
          </div>
          <div style={{ height: 420, position: 'relative', background: ready && reach !== 'blocked' ? '#fff' : 'repeating-linear-gradient(45deg,#f4f4f5,#f4f4f5 12px,#eeeef0 12px,#eeeef0 24px)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            {ready && reach === 'blocked' ? (
              <div data-testid="preview-blocked" style={{ maxWidth: 340, textAlign: 'center', background: '#ffffffcc', border: `1px solid ${c.border2}`, borderRadius: 9, padding: '18px 20px' }}>
                <div style={{ fontFamily: font.display, fontWeight: 600, fontSize: 14, marginBottom: 6 }}>App is running ✓</div>
                <div style={{ fontSize: 12, color: c.muted, lineHeight: 1.5, marginBottom: 14 }}>Your browser is blocking the inline preview because it's served over plain HTTP. The sandbox itself is healthy — open it in a new tab to view it.</div>
                <Btn variant="primary" data-testid="preview-open-newtab" onClick={() => window.open(previewURL, '_blank')}>Open in new tab ↗</Btn>
                <a onClick={() => setNonce((n) => n + 1)} className="dc-hoverink" style={{ display: 'block', marginTop: 10, fontSize: 11.5, color: c.muted2, cursor: 'pointer' }}>Retry inline</a>
              </div>
            ) : ready ? (
              <iframe key={`${previewURL}-${nonce}`} src={previewURL} title="preview" data-testid="preview" style={{ width: '100%', height: '100%', border: 'none' }} />
            ) : running && previewURL && sb?.preview?.status !== 'none' ? (
              <div style={{ ...mono, fontSize: 11.5, color: c.muted, background: '#ffffffcc', border: `1px dashed ${c.border2}`, borderRadius: 7, padding: '10px 16px', textAlign: 'center' }} data-testid="preview-starting">
                <div style={{ animation: 'pulse 1.4s ease-in-out infinite' }}>▍ starting dev server…</div>
                <div style={{ fontSize: 10.5, color: c.muted2, marginTop: 4 }}>waiting for the first response — this refreshes automatically</div>
              </div>
            ) : (
              <div style={{ ...mono, fontSize: 11.5, color: c.muted2, background: '#ffffffcc', border: `1px dashed ${c.border2}`, borderRadius: 7, padding: '8px 14px' }} data-testid="preview-empty">
                {!sb ? 'No sandbox yet — create one from the header' : sb.preview?.status === 'none' ? 'No public endpoint — worker running' : 'Sandbox not running'}
              </div>
            )}
          </div>
        </Card>

        {/* processes */}
        <ProcessesCard sb={sb} running={running} procs={procs} onError={onError} />

        <RuntimeCard appId={app.id} onApplyRuntime={onApplyRuntime} canApply={canApply} />
      </div>

      <AgentChat sb={sb} onError={onError} refresh={refresh} />
    </div>
  )
}

function ProcessesCard({ sb, running, procs, onError }: { sb: Sandbox | null; running: boolean; procs: Process[]; onError: (m: string) => void }) {
  const [logsFor, setLogsFor] = useState<string | null>(null)
  const [lines, setLines] = useState<string[]>([])
  const [loading, setLoading] = useState(false)
  const logRef = useRef<HTMLDivElement>(null)
  useEffect(() => { if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight }, [lines])

  const viewLogs = async (name: string) => {
    if (!sb) return
    if (logsFor === name) { setLogsFor(null); return }
    setLogsFor(name); setLines([]); setLoading(true)
    try { const r = await api.getProcessLogs(sb.id, name, 200); setLines(r.lines) }
    catch (e) { onError((e as Error).message) } finally { setLoading(false) }
  }

  return (
    <Card style={{ padding: 16 }}>
      <div style={{ display: 'flex', alignItems: 'baseline', marginBottom: 10 }}>
        <H>Processes</H>
        <span style={{ marginLeft: 'auto', ...mono, fontSize: 10.5, color: c.muted2 }}>supervised · auto-restart</span>
      </div>
      {procs.length === 0 ? (
        <div style={{ color: c.muted2, fontSize: 12.5 }} data-testid="processes-empty">No processes {running ? 'reported' : '— sandbox not running'}.</div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '1.2fr .9fr .9fr .6fr .7fr auto', gap: '0 12px', fontSize: 12.5, alignItems: 'center' }} data-testid="processes-list">
          {['Name', 'Kind', 'Status', 'PID', 'Restarts', ''].map((h, i) => (
            <div key={i} style={{ color: c.muted2, fontSize: 11, textTransform: 'uppercase', letterSpacing: '.7px', padding: '6px 0', borderBottom: `1px solid ${c.border}` }}>{h}</div>
          ))}
          {procs.map((p) => (
            <Fragment key={p.name}>
              <div style={{ ...mono, padding: '9px 0' }}>{p.name}</div>
              <div style={{ color: c.muted, padding: '9px 0' }}>{p.kind}</div>
              <div style={{ padding: '9px 0' }}><Pill tone={p.running ? 'good' : 'neutral'} dot>{p.running ? 'running' : 'stopped'}</Pill></div>
              <div style={{ ...mono, color: c.muted, padding: '9px 0' }}>{p.pid || '—'}</div>
              <div style={{ ...mono, color: c.muted, padding: '9px 0' }}>{p.restarts ?? 0}</div>
              <div style={{ padding: '9px 0', textAlign: 'right' }}>
                <a onClick={() => viewLogs(p.name)} className="dc-hoverink" data-testid={`process-logs-${p.name}`} style={{ fontSize: 12, color: logsFor === p.name ? c.fg : c.muted2, cursor: 'pointer' }}>{logsFor === p.name ? 'Hide' : 'Logs'}</a>
              </div>
            </Fragment>
          ))}
        </div>
      )}
      {logsFor && (
        <div style={{ marginTop: 12 }}>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: 6 }}>
            <span style={{ ...mono, fontSize: 11.5, color: c.muted }}>{logsFor} — last 200 lines</span>
            <a onClick={() => viewLogs(logsFor)} className="dc-hoverink" style={{ marginLeft: 'auto', fontSize: 11.5, color: c.link, cursor: 'pointer' }}>Refresh</a>
          </div>
          <div ref={logRef} data-testid="process-log-output" style={{ background: '#0a0a0a', border: `1px solid ${c.border2}`, borderRadius: 7, padding: '10px 12px', ...mono, fontSize: 11.5, color: '#d4d4d8', lineHeight: 1.6, maxHeight: 260, overflow: 'auto', whiteSpace: 'pre-wrap' }}>
            {loading ? 'loading…' : lines.length === 0 ? '(no output)' : lines.join('\n')}
          </div>
        </div>
      )}
    </Card>
  )
}

function RuntimeCard({ appId, onApplyRuntime, canApply }: { appId: string; onApplyRuntime: () => void; canApply: boolean }) {
  const [eff, setEff] = useState<{ command?: string; port?: number; health?: string } | null>(null)
  const [valid, setValid] = useState<boolean | null>(null)
  const [present, setPresent] = useState(false)
  const [detected, setDetected] = useState<{ preset: string; confidence: string } | null>(null)
  useEffect(() => {
    api.appManifest(appId).then((m) => {
      const w = m.effective?.web
      if (w) setEff({ command: w.command, port: w.port, health: w.health_path })
      setPresent(m.present)
      setValid(m.present ? m.validation?.valid ?? null : null)
    }).catch(() => {})
    // Advisory detection — surfaced so the user can one-click apply it.
    api.runtimeInspect(appId).then((r) => {
      const s = r.suggestions.find((x) => x.preset === r.default_suggestion) || r.suggestions[0]
      if (s?.suggested_manifest) setDetected({ preset: s.preset, confidence: s.confidence })
    }).catch(() => {})
  }, [appId])
  const showApply = !present && !!detected // no manifest yet + something detected
  return (
    <Card style={{ padding: 16 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
        <H>Runtime</H>
        {valid !== null && <Pill tone={valid ? 'good' : 'bad'}>{valid ? 'sandbox.yaml valid' : 'sandbox.yaml invalid'}</Pill>}
        {showApply && <Pill tone="warn">detected: {detected!.preset}</Pill>}
        <span style={{ marginLeft: 'auto', fontSize: 11.5, color: c.muted2 }}>Runtime config — never touches your source</span>
      </div>
      <pre style={{ background: c.bg, border: `1px solid ${c.border}`, borderRadius: 7, padding: '12px 14px', ...mono, fontSize: 12, color: c.fg2, margin: '10px 0 0', overflowX: 'auto', lineHeight: 1.6 }}>
{eff ? `command: ${eff.command || '(default)'}\nport: ${eff.port ?? 3000}\nhealth: ${eff.health || '/'}` : 'no sandbox.yaml — using defaults'}
      </pre>
      {showApply && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 12 }}>
          <span style={{ fontSize: 12, color: c.muted }}>Detected <b style={{ color: c.fg }}>{detected!.preset}</b> ({detected!.confidence}). Apply the recommended <span style={{ ...mono, fontSize: 11.5 }}>sandbox.yaml</span> so the preview boots.</span>
          <Btn sm variant="primary" disabled={!canApply} title={canApply ? '' : 'Start the sandbox first'} onClick={onApplyRuntime} data-testid="apply-runtime" style={{ marginLeft: 'auto' }}>Apply detected runtime</Btn>
        </div>
      )}
    </Card>
  )
}

function AgentChat({ sb, onError, refresh }: { sb: Sandbox | null; onError: (m: string) => void; refresh: () => void }) {
  const [agent, setAgent] = useState('opencode')
  const [model, setModel] = useState('')
  const [cont, setCont] = useState(true) // continue the last agent session by default
  const [text, setText] = useState('')
  const [msgs, setMsgs] = useState<Msg[]>([])
  const [running, setRunning] = useState(false)
  const [resolved, setResolved] = useState('')
  const esRef = useRef<EventSource | null>(null)
  const scrollRef = useRef<HTMLDivElement>(null)
  useEffect(() => () => esRef.current?.close(), [])
  useEffect(() => { if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight }, [msgs, running])

  const send = async () => {
    if (!sb || sb.status !== 'running' || !text.trim() || running) return
    const prompt = text.trim()
    setText('')
    setMsgs((m) => [...m, { role: 'user', text: prompt }])
    setResolved(''); setRunning(true)
    try {
      const t = await api.submitTask(sb.id, prompt, agent, model || undefined, cont)
      let agentText = ''
      const es = new EventSource(api.taskEventsURL(sb.id, t.id))
      esRef.current = es
      es.addEventListener('status', (m) => { try { const j = JSON.parse((m as MessageEvent).data); if (j.model) setResolved(j.model) } catch { /* */ } })
      es.addEventListener('message', (m) => {
        try { const j = JSON.parse((m as MessageEvent).data); if (j.role === 'agent' && j.text) { agentText += j.text; setMsgs((cur) => { const copy = [...cur]; const last = copy[copy.length - 1]; if (last && last.role === 'agent' && !last.done) last.text = agentText; else copy.push({ role: 'agent', text: agentText, taskId: t.id }); return copy }) } } catch { /* */ }
      })
      es.addEventListener('done', () => {
        es.close(); setRunning(false)
        setMsgs((cur) => { const copy = [...cur]; const last = copy[copy.length - 1]; if (last && last.role === 'agent') last.done = true; else copy.push({ role: 'agent', text: '(done)', taskId: t.id, done: true }); return copy })
        refresh()
      })
      es.onerror = () => { es.close(); setRunning(false) }
    } catch (e) { setRunning(false); onError((e as Error).message) }
  }

  return (
    <Card style={{ display: 'flex', flexDirection: 'column', height: 640, overflow: 'hidden' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 14px', borderBottom: `1px solid ${c.border}`, background: c.panel3 }}>
        <H size={14}>Agent</H>
        <div style={{ marginLeft: 'auto', display: 'flex', gap: 6, alignItems: 'center' }}>
          <label title="Continue the sandbox's most recent agent session instead of starting fresh" style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 11.5, color: cont ? c.fg : c.muted2, cursor: 'pointer' }} data-testid="task-continue">
            <input type="checkbox" checked={cont} onChange={(e) => setCont(e.target.checked)} style={{ accentColor: c.ink, width: 13, height: 13 }} />
            Continue
          </label>
          <select value={agent} onChange={(e) => { setAgent(e.target.value); setModel('') }} data-testid="task-agent" style={selStyle}>
            <option value="claude-code">Claude Code</option><option value="opencode">OpenCode</option>
            {/* Codex hidden from the run picker until it's behind the auth proxy — the adapter is wired but subscription auth can't be secured yet. */}
          </select>
          <select value={model} onChange={(e) => setModel(e.target.value)} data-testid="task-model" style={selStyle}>
            <option value="">Default model</option>
            {agent === 'claude-code' && <><option value="sonnet">Sonnet</option><option value="opus">Opus</option><option value="haiku">Haiku</option></>}
            {agent === 'opencode' && <><option value="opencode/glm-5">GLM-5</option><option value="opencode/kimi-k2.6">Kimi K2.6</option><option value="opencode/deepseek-v4-pro">DeepSeek V4 Pro</option><option value="opencode/minimax-m3">MiniMax M3</option></>}
          </select>
        </div>
      </div>
      <div ref={scrollRef} style={{ flex: 1, overflowY: 'auto', padding: 14, display: 'flex', flexDirection: 'column', gap: 10 }}>
        {msgs.length === 0 && !running && (
          <div style={{ margin: 'auto', textAlign: 'center', color: c.muted2, fontSize: 12.5, maxWidth: 220 }}>Ask the agent to change this app — it works inside the sandbox and nothing is committed until you approve.</div>
        )}
        {msgs.map((m, i) => (
          <div key={i} style={{ display: 'flex', justifyContent: m.role === 'user' ? 'flex-end' : 'flex-start' }}>
            <div style={{ maxWidth: '85%', fontSize: 12.5, borderRadius: 9, padding: '8px 11px', whiteSpace: 'pre-wrap', background: m.role === 'user' ? c.ink : c.panel2, color: m.role === 'user' ? '#fff' : c.fg, border: m.role === 'user' ? 'none' : `1px solid ${c.border}` }}>
              {m.text}
            </div>
          </div>
        ))}
        {resolved && <div style={{ ...mono, fontSize: 10.5, color: c.muted2 }}>▸ {resolved}</div>}
        {running && <div style={{ ...mono, fontSize: 11.5, color: c.muted2, animation: 'pulse 1.4s ease-in-out infinite' }}>▍ working…</div>}
      </div>
      <div style={{ display: 'flex', gap: 8, padding: 10, borderTop: `1px solid ${c.border}`, background: c.panel3 }}>
        <textarea value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send() } }} placeholder={sb?.status === 'running' ? 'Message the agent…' : 'Start the sandbox to run tasks'} data-testid="task-prompt" rows={1} style={{ flex: 1, background: '#fff', border: `1px solid ${c.border2}`, borderRadius: 7, padding: '8px 11px', color: c.fg, fontSize: 12.5, fontFamily: font.sans, resize: 'none' }} />
        <Btn variant="primary" onClick={send} disabled={!sb || sb.status !== 'running' || running} data-testid="run-task">Send</Btn>
      </div>
    </Card>
  )
}
const selStyle: React.CSSProperties = { background: c.bg, border: `1px solid ${c.border2}`, borderRadius: 7, padding: '5px 7px', color: c.fg, fontSize: 11.5, fontFamily: font.sans }

// ---------- FILES ----------
type TreeNode = { name: string; path: string; type: 'file' | 'dir'; size?: number; children: TreeNode[] }

function buildFileTree(entries: FileEntry[]): TreeNode[] {
  const root: TreeNode = { name: '', path: '', type: 'dir', children: [] }
  const dirs = new Map<string, TreeNode>([['', root]])
  for (const e of [...entries].sort((a, b) => a.path.localeCompare(b.path))) {
    const parts = e.path.split('/')
    const parentPath = parts.slice(0, -1).join('/')
    const parent = dirs.get(parentPath) || root
    const node: TreeNode = { name: parts[parts.length - 1], path: e.path, type: e.type, size: e.size, children: [] }
    parent.children.push(node)
    if (e.type === 'dir') dirs.set(e.path, node)
  }
  const sortNodes = (nodes: TreeNode[]) => {
    nodes.sort((a, b) => (a.type !== b.type ? (a.type === 'dir' ? -1 : 1) : a.name.localeCompare(b.name)))
    nodes.forEach((n) => sortNodes(n.children))
  }
  sortNodes(root.children)
  return root.children
}

function FilesTab({ sb, onError, toast }: { sb: Sandbox | null; onError: (m: string) => void; toast: (m: string) => void }) {
  const sandboxId = sb?.id
  const [entries, setEntries] = useState<FileEntry[]>([])
  const [open, setOpen] = useState<Record<string, boolean>>({})
  const [path, setPath] = useState<string | null>(null)
  const [content, setContent] = useState('')
  const [orig, setOrig] = useState('')
  const [view, setView] = useState<'idle' | 'loading' | 'ok' | 'toobig' | 'binary'>('idle')
  const [saving, setSaving] = useState(false)
  const [treeLoading, setTreeLoading] = useState(false)
  const taRef = useRef<HTMLTextAreaElement>(null)
  const gutRef = useRef<HTMLDivElement>(null)
  const dirty = view === 'ok' && content !== orig

  const loadTree = useCallback(() => {
    if (!sandboxId) return
    setTreeLoading(true)
    api.listFiles(sandboxId, { recursive: true }).then((r) => setEntries(r.entries || [])).catch((e) => onError((e as Error).message)).finally(() => setTreeLoading(false))
  }, [sandboxId, onError])
  useEffect(() => { loadTree() }, [loadTree])

  const openFile = async (p: string) => {
    if (dirty && !window.confirm('Discard unsaved changes?')) return
    setPath(p); setView('loading')
    try {
      const body = (await api.getWorkspaceFile(sandboxId!, p)) ?? ''
      if (body.includes('\u0000')) { setView('binary'); return }
      setContent(body); setOrig(body); setView('ok')
    } catch (e) {
      const m = (e as Error).message
      if (m.startsWith('400')) setView('toobig')
      else { setView('idle'); onError(m) }
    }
  }
  const save = async () => {
    if (!sandboxId || path == null || view !== 'ok') return
    setSaving(true)
    try { await api.writeAppFile(sandboxId, path, content); setOrig(content); toast('Saved'); loadTree() }
    catch (e) { onError((e as Error).message) } finally { setSaving(false) }
  }
  const onKey = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 's') { e.preventDefault(); save(); return }
    if (e.key === 'Tab') {
      e.preventDefault()
      const ta = e.currentTarget, s = ta.selectionStart, en = ta.selectionEnd
      setContent(content.slice(0, s) + '  ' + content.slice(en))
      requestAnimationFrame(() => { ta.selectionStart = ta.selectionEnd = s + 2 })
    }
  }

  if (!sandboxId) return <Card style={{ padding: 18, color: c.muted, fontSize: 13 }}>Create a sandbox to browse and edit files.</Card>

  const lines = content.length ? content.split('\n').length : 1
  const renderNodes = (nodes: TreeNode[], depth: number): React.ReactNode =>
    nodes.map((n) => n.type === 'dir' ? (
      <Fragment key={n.path}>
        <div className="dc-hoverink" onClick={() => setOpen((o) => ({ ...o, [n.path]: !o[n.path] }))} style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '3px 8px', paddingLeft: 8 + depth * 13, cursor: 'pointer', fontSize: 12.5, color: c.fg2, userSelect: 'none' }}>
          <span style={{ width: 9, color: c.muted2, fontSize: 9 }}>{open[n.path] ? '▾' : '▸'}</span>{n.name}
        </div>
        {open[n.path] && renderNodes(n.children, depth + 1)}
      </Fragment>
    ) : (
      <div key={n.path} className="dc-hoverink" onClick={() => openFile(n.path)} title={`${n.path}${n.size != null ? ` · ${n.size} B` : ''}`} style={{ display: 'flex', alignItems: 'center', paddingLeft: 21 + depth * 13, paddingRight: 8, paddingTop: 3, paddingBottom: 3, cursor: 'pointer', fontSize: 12.5, borderRadius: 5, background: path === n.path ? c.panel2 : 'transparent', color: path === n.path ? c.fg : c.muted, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
        <span style={{ ...mono, fontSize: 12.5 }}>{n.name}</span>
      </div>
    ))

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '270px minmax(0,1fr)', gap: 14, alignItems: 'start' }}>
      <Card style={{ padding: 10, maxHeight: 660, overflow: 'auto' }} data-testid="files-tree">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '2px 6px 8px' }}>
          <H size={13}>Files</H>
          <div style={{ display: 'flex', gap: 9, alignItems: 'center' }}>
            <span onClick={loadTree} title="Refresh" className="dc-hoverink" style={{ cursor: 'pointer', fontSize: 13, color: c.muted2 }}>⟳</span>
            <a href={api.exportUrl(sandboxId)} title="Download workspace (.zip)" style={{ fontSize: 13, color: c.muted2, textDecoration: 'none' }}>⬇</a>
          </div>
        </div>
        {treeLoading && entries.length === 0 ? <div style={{ padding: 8, color: c.muted2, fontSize: 12 }}>Loading…</div>
          : entries.length === 0 ? <div style={{ padding: 8, color: c.muted2, fontSize: 12 }}>No files.</div>
          : renderNodes(buildFileTree(entries), 0)}
      </Card>

      <Card style={{ padding: 0, overflow: 'hidden', minHeight: 440 }}>
        {path == null ? (
          <div style={{ padding: 44, textAlign: 'center', color: c.muted2, fontSize: 13 }}>Select a file to view or edit.</div>
        ) : (
          <>
            <div style={{ display: 'flex', alignItems: 'center', gap: 9, padding: '10px 14px', borderBottom: `1px solid ${c.border}`, background: c.panel3 }}>
              <span style={{ ...mono, fontSize: 12.5, color: c.fg, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{path}</span>
              {dirty && <span title="Unsaved changes" style={{ width: 7, height: 7, borderRadius: '50%', background: c.warn, flex: '0 0 auto' }} />}
              <div style={{ marginLeft: 'auto', display: 'flex', gap: 8, flex: '0 0 auto' }}>
                <Btn sm onClick={() => openFile(path)} disabled={saving}>Reload</Btn>
                <Btn sm variant="primary" onClick={save} disabled={!dirty || saving}>{saving ? 'Saving…' : 'Save'}</Btn>
              </div>
            </div>
            {view === 'loading' ? <div style={{ padding: 30, color: c.muted2, fontSize: 13 }}>Loading…</div>
              : view === 'toobig' ? <div style={{ padding: 30, color: c.muted2, fontSize: 13 }}>Larger than the 2&nbsp;MiB editor cap — <a href={`/v1/sandboxes/${sandboxId}/files/content?path=${encodeURIComponent(path)}`} style={{ color: c.link }}>open raw</a>.</div>
              : view === 'binary' ? <div style={{ padding: 30, color: c.muted2, fontSize: 13 }}>Binary file — not shown in the editor.</div>
              : (
                <div style={{ display: 'flex', maxHeight: 580, overflow: 'hidden' }}>
                  <div ref={gutRef} style={{ ...mono, fontSize: 12.5, lineHeight: '20px', textAlign: 'right', padding: '10px 8px', color: c.faint, background: c.panel3, borderRight: `1px solid ${c.border}`, overflow: 'hidden', userSelect: 'none', whiteSpace: 'pre' }}>
                    {Array.from({ length: lines }, (_, i) => i + 1).join('\n')}
                  </div>
                  <textarea ref={taRef} value={content} onChange={(e) => setContent(e.target.value)} onKeyDown={onKey} onScroll={() => { if (gutRef.current && taRef.current) gutRef.current.scrollTop = taRef.current.scrollTop }} spellCheck={false} style={{ ...mono, flex: 1, fontSize: 12.5, lineHeight: '20px', padding: '10px 12px', border: 'none', outline: 'none', resize: 'none', minHeight: 420, maxHeight: 580, color: c.fg, background: c.panel, whiteSpace: 'pre', overflow: 'auto', tabSize: 2 }} />
                </div>
              )}
          </>
        )}
      </Card>
    </div>
  )
}

// ---------- GIT ----------
function DiffView({ text }: { text: string }) {
  return (
    <div style={{ ...mono, fontSize: 12, lineHeight: '18px', overflow: 'auto', maxHeight: 580, padding: '6px 0' }}>
      {text.split('\n').map((ln, i) => {
        let bg = 'transparent', col = c.fg2
        if (ln.startsWith('@@')) { bg = c.panel2; col = c.muted }
        else if (/^(diff |index |--- |\+\+\+ )/.test(ln)) { col = c.muted2 }
        else if (ln.startsWith('+')) { bg = 'rgba(21,128,61,.10)'; col = c.good }
        else if (ln.startsWith('-')) { bg = 'rgba(220,38,38,.10)'; col = c.bad }
        return <div key={i} style={{ background: bg, color: col, padding: '0 12px', whiteSpace: 'pre' }}>{ln || ' '}</div>
      })}
    </div>
  )
}

function GitTab({ appId, onError, toast, goSettings }: { appId: string; onError: (m: string) => void; toast: (m: string) => void; goSettings: () => void }) {
  const [st, setSt] = useState<GitStatus | null>(null)
  const [sel, setSel] = useState<Record<string, boolean>>({})
  const [msg, setMsg] = useState('')
  const [busy, setBusy] = useState(false)
  const [pushing, setPushing] = useState(false)
  const [showRuntime, setShowRuntime] = useState(false)
  const [diffPath, setDiffPath] = useState<string | null>(null)
  const [diff, setDiff] = useState('')
  const [diffLoading, setDiffLoading] = useState(false)
  const load = useCallback(() => api.gitStatus(appId).then((s) => { setSt(s); const init: Record<string, boolean> = {}; (s.files || []).forEach((f) => (init[f.path] = true)); setSel(init) }).catch((e) => onError((e as Error).message)), [appId, onError])
  useEffect(() => { load() }, [load])

  const files: GitFile[] = st?.files || []
  const runtimeFiles: GitFile[] = st?.runtime_files || []
  const selected = files.filter((f) => sel[f.path]).map((f) => f.path)

  const viewDiff = async (p: string) => {
    setDiffPath(p); setDiffLoading(true); setDiff('')
    try { const d = await api.gitDiff(appId, p); setDiff(d.diff || (d.available ? '(no textual diff — likely a binary or mode change)' : d.reason || 'unavailable')) }
    catch (e) { onError((e as Error).message) } finally { setDiffLoading(false) }
  }
  const commit = async () => {
    if (!msg.trim()) return
    setBusy(true)
    try { const r = await api.gitCommit(appId, { message: msg.trim(), paths: selected }); if (r.committed) { toast(`Committed ${r.sha?.slice(0, 7)}`); setMsg(''); setDiffPath(null); load() } else onError(r.reason || 'nothing committed') } catch (e) { onError((e as Error).message) } finally { setBusy(false) }
  }
  const push = async () => {
    setPushing(true)
    try {
      const r = await api.gitPush(appId, {})
      if (r.pushed) toast(`Pushed ${r.commits ?? ''} commit${r.commits === 1 ? '' : 's'}${r.branch ? ` → ${r.branch}` : ''}`.replace(/\s+/g, ' ').trim())
      else onError(r.reason === 'no_credential' ? 'No Git credential — add one in Settings → Git credentials.' : (r.reason || 'push failed'))
      load()
    } catch (e) { onError((e as Error).message) } finally { setPushing(false) }
  }

  if (st && !st.available) return <Card style={{ padding: 16, color: c.muted2, fontSize: 13 }}>{st.reason === 'not_a_git_repo' ? 'This app is not a Git repository.' : 'Git is unavailable — start the sandbox.'}</Card>

  const statusColor = (s: string) => (s.startsWith('add') || s === 'untracked' ? c.good : s.startsWith('del') ? c.bad : c.warn)
  const badge = (s: string) => (s === 'untracked' ? '?' : s[0].toUpperCase())
  const fileRow = (f: GitFile, stageable: boolean) => (
    <div key={f.path} className="dc-hoverborder" style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '7px 9px', border: `1px solid ${diffPath === f.path ? c.border2 : c.border}`, borderRadius: 7, marginBottom: 5, background: diffPath === f.path ? c.panel2 : c.panel }}>
      {stageable && <span onClick={() => setSel((s) => ({ ...s, [f.path]: !s[f.path] }))} style={{ width: 15, height: 15, borderRadius: 4, border: `1px solid ${c.border2}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10, cursor: 'pointer', background: sel[f.path] ? c.ink : '#fff', color: '#fff', flex: '0 0 auto' }}>{sel[f.path] ? '✓' : ''}</span>}
      <span title={f.status} style={{ ...mono, fontSize: 10.5, fontWeight: 700, width: 14, textAlign: 'center', color: statusColor(f.status), flex: '0 0 auto' }}>{badge(f.status)}</span>
      <span onClick={() => viewDiff(f.path)} className="dc-hoverink" style={{ ...mono, fontSize: 12.5, cursor: 'pointer', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{f.path}</span>
    </div>
  )

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '360px minmax(0,1fr)', gap: 14, alignItems: 'start' }}>
      <Card style={{ padding: 14 }} data-testid="git-panel">
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10, flexWrap: 'wrap' }}>
          <H size={14}>Changes</H>
          <span style={{ ...mono, fontSize: 11, color: c.muted, background: c.panel2, border: `1px solid ${c.border}`, borderRadius: 5, padding: '2px 7px' }}>{st?.branch || 'main'}</span>
          {(st?.ahead ?? 0) > 0 && <span title="commits ahead of remote" style={{ fontSize: 11, color: c.good }}>↑{st?.ahead}</span>}
          {(st?.behind ?? 0) > 0 && <span title="commits behind remote" style={{ fontSize: 11, color: c.warn }}>↓{st?.behind}</span>}
          <span style={{ marginLeft: 'auto', fontSize: 11.5, color: c.muted2 }}>{files.length ? `${files.length} changed` : 'clean'}</span>
          <span onClick={load} title="Refresh" className="dc-hoverink" style={{ cursor: 'pointer', color: c.muted2 }}>⟳</span>
        </div>
        {files.length === 0 ? <div style={{ color: c.muted2, fontSize: 12.5, padding: '2px 0 8px' }}>No user changes.</div> : (
          <>
            <div style={{ display: 'flex', gap: 12, marginBottom: 8, fontSize: 11.5 }}>
              <span onClick={() => setSel(Object.fromEntries(files.map((f) => [f.path, true])))} className="dc-hoverink" style={{ cursor: 'pointer', color: c.link }}>Select all</span>
              <span onClick={() => setSel({})} className="dc-hoverink" style={{ cursor: 'pointer', color: c.link }}>None</span>
            </div>
            {files.map((f) => fileRow(f, true))}
          </>
        )}
        {runtimeFiles.length > 0 && (
          <div style={{ marginTop: 6 }}>
            <div onClick={() => setShowRuntime((v) => !v)} className="dc-hoverink" style={{ cursor: 'pointer', fontSize: 11.5, color: c.muted2, padding: '4px 0' }}>{showRuntime ? '▾' : '▸'} {runtimeFiles.length} runtime-generated (sandbox.yaml, lockfiles…)</div>
            {showRuntime && <div style={{ marginTop: 4 }}>{runtimeFiles.map((f) => fileRow(f, false))}</div>}
          </div>
        )}
        <Input value={msg} onChange={(e) => setMsg(e.target.value)} placeholder="Commit message…" style={{ width: '100%', margin: '10px 0 8px', fontSize: 13, fontFamily: font.sans }} />
        <div style={{ display: 'flex', gap: 8 }}>
          <Btn variant="primary" disabled={busy || !msg.trim() || selected.length === 0} onClick={commit} style={{ fontSize: 13 }}>Commit{selected.length ? ` (${selected.length})` : ''}</Btn>
          <Btn disabled={pushing} onClick={push} title="Push commits to the remote">{pushing ? 'Pushing…' : `Push${(st?.ahead ?? 0) > 0 ? ` ↑${st?.ahead}` : ''}`}</Btn>
        </div>
        <div style={{ fontSize: 11.5, color: c.muted2, marginTop: 8 }}>Push needs a Git credential — <span onClick={goSettings} className="dc-hoverink" style={{ cursor: 'pointer', color: c.link }}>manage in Settings</span>.</div>
      </Card>

      <Card style={{ padding: 0, overflow: 'hidden', minHeight: 440 }}>
        {diffPath == null ? <div style={{ padding: 44, textAlign: 'center', color: c.muted2, fontSize: 13 }}>Click a changed file to see its diff.</div> : (
          <>
            <div style={{ padding: '10px 14px', borderBottom: `1px solid ${c.border}`, background: c.panel3, ...mono, fontSize: 12.5, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{diffPath}</div>
            {diffLoading ? <div style={{ padding: 24, color: c.muted2, fontSize: 13 }}>Loading diff…</div> : <DiffView text={diff} />}
          </>
        )}
      </Card>
    </div>
  )
}

// ---------- CONFIG ----------
function ConfigTab({ appId, onError }: { appId: string; onError: (m: string) => void }) {
  const [items, setItems] = useState<ConfigItem[]>([])
  const [k, setK] = useState(''); const [v, setV] = useState(''); const [secret, setSecret] = useState(true)
  const load = useCallback(() => api.listConfig(appId).then(setItems).catch((e) => onError((e as Error).message)), [appId, onError])
  useEffect(() => { load() }, [load])
  const add = async () => { if (!k.trim()) return; try { await api.createConfig(appId, { key: k.trim(), value: v, sensitive: secret, access_policy: 'control_plane_only' }); setK(''); setV(''); load() } catch (e) { onError((e as Error).message) } }
  return (
    <Card style={{ padding: 16, maxWidth: 760 }} data-testid="config-panel">
      <div style={{ display: 'flex', alignItems: 'baseline', marginBottom: 6 }}>
        <H>Config &amp; Secrets</H>
        <span style={{ marginLeft: 'auto', fontSize: 11.5, color: c.muted2 }}>Secrets are encrypted at rest and never shown again</span>
      </div>
      {items.length === 0 ? <div style={{ color: c.muted2, fontSize: 12.5, padding: '10px 0' }}>No config yet. Add a key below.</div> : items.map((it) => (
        <div key={it.key} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 12px', border: `1px solid ${c.border}`, borderRadius: 7, marginBottom: 6, background: c.panel2 }}>
          <span style={{ ...mono, fontSize: 12.5, fontWeight: 500, minWidth: 160 }}>{it.key}</span>
          <span style={{ ...mono, fontSize: 12, color: c.muted }}>{it.sensitive ? '••••••' : it.value}</span>
          <a onClick={() => api.deleteConfig(appId, it.key).then(load)} className="dc-hoverink" style={{ marginLeft: 'auto', color: c.muted2, fontSize: 12, cursor: 'pointer' }}>Remove</a>
        </div>
      ))}
      <div style={{ display: 'flex', gap: 8, marginTop: 12, alignItems: 'center' }}>
        <Input mono value={k} onChange={(e) => setK(e.target.value)} placeholder="KEY" style={{ width: 180 }} />
        <Input mono value={v} onChange={(e) => setV(e.target.value)} placeholder="value" type={secret ? 'password' : 'text'} style={{ flex: 1 }} />
        <label onClick={() => setSecret((s) => !s)} style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer', fontSize: 12.5, color: c.muted }}>
          <span style={{ width: 15, height: 15, borderRadius: 4, border: `1px solid ${c.border2}`, background: secret ? c.ink : '#fff', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10 }}>{secret ? '✓' : ''}</span>secret
        </label>
        <Btn variant="primary" onClick={add}>Add</Btn>
      </div>
    </Card>
  )
}

// ---------- SNAPSHOTS ----------
function SnapshotsTab({ appId, appName, onError, toast, refresh, sb }: { appId: string; appName: string; onError: (m: string) => void; toast: (m: string) => void; refresh: () => void; sb: Sandbox | null }) {
  const [snaps, setSnaps] = useState<Snapshot[]>([])
  const load = useCallback(() => api.listAppSnapshots(appId).then(setSnaps).catch((e) => onError((e as Error).message)), [appId, onError])
  useEffect(() => { load() }, [load])
  return (
    <div style={{ maxWidth: 760 }}>
      <Card style={{ padding: 16, marginBottom: 16 }}>
        <H style={{ marginBottom: 6 }}>Snapshots — save the whole environment</H>
        <div style={{ color: c.muted, fontSize: 12.5 }}>A snapshot freezes the <b style={{ color: c.fg }}>entire workspace</b> — your code plus installed packages, build output, and data — so you can roll back or clone the exact running setup in seconds.</div>
      </Card>
      {snaps.length === 0 ? (
        <div style={{ border: `1px dashed ${c.border2}`, borderRadius: 10, padding: 28, textAlign: 'center', color: c.muted2, fontSize: 12.5 }}>
          No snapshots yet. <a onClick={() => { if (sb) api.createSnapshot(sb.id, `${appName}-${Date.now()}`).then(() => { toast('Snapshot captured'); load() }).catch((e) => onError((e as Error).message)) }} style={{ color: c.link, cursor: 'pointer' }}>Take one now</a> — stop the sandbox first for a consistent capture.
        </div>
      ) : snaps.map((s) => (
        <Card key={s.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '13px 16px', marginBottom: 8 }}>
          <div>
            <div style={{ ...mono, fontSize: 12.5 }}>{s.name}</div>
            <div style={{ color: c.muted2, fontSize: 11.5 }}>{new Date(s.created_at).toLocaleString()} · {s.size_bytes ? `${Math.round(s.size_bytes / 1024)} KB` : '—'}</div>
          </div>
          <div style={{ marginLeft: 'auto', display: 'flex', gap: 6 }}>
            <Btn sm onClick={() => { if (window.confirm(`Roll back to "${s.name}"? Replaces the current sandbox.`)) api.restoreApp(appId, s.id).then(() => { toast('Rolled back'); refresh() }).catch((e) => onError((e as Error).message)) }}>Roll back</Btn>
            <Btn sm onClick={() => { const name = window.prompt('Duplicate into a new app named:', `${appName} copy`); if (name) api.forkApp(appId, s.id, name.trim()).then(() => toast('Duplicated')).catch((e) => onError((e as Error).message)) }}>Duplicate</Btn>
          </div>
        </Card>
      ))}
    </div>
  )
}

// ---------- ACTIVITY ----------
function ActivityTab({ appId, onError }: { appId: string; onError: (m: string) => void }) {
  const [events, setEvents] = useState<AppEvent[]>([])
  useEffect(() => { api.listAppEvents(appId).then(setEvents).catch((e) => onError((e as Error).message)) }, [appId, onError])
  return (
    <Card style={{ padding: 16, maxWidth: 860 }} data-testid="activity-panel">
      <div style={{ display: 'flex', alignItems: 'baseline', marginBottom: 10 }}>
        <H>Activity</H>
        <span style={{ marginLeft: 'auto', fontSize: 11.5, color: c.muted2 }}>Durable timeline — survives restarts</span>
      </div>
      {events.length === 0 ? <div style={{ color: c.muted2, fontSize: 12.5 }}>No activity yet.</div> : events.map((ev) => (
        <div key={ev.id} style={{ display: 'grid', gridTemplateColumns: '74px 160px 1fr', gap: 12, alignItems: 'baseline', padding: '6px 0', borderBottom: `1px solid ${c.panel2}`, fontSize: 12.5 }}>
          <span style={{ ...mono, fontSize: 11, color: c.muted2 }}>{new Date(ev.created_at).toLocaleTimeString()}</span>
          <span><Pill tone={ev.severity === 'error' ? 'bad' : ev.severity === 'warning' ? 'warn' : 'neutral'}>{ev.type}</Pill></span>
          <span style={{ color: c.fg }}>{ev.message}</span>
        </div>
      ))}
    </Card>
  )
}
